@schedule
Feature: Validate Schedule JSON

  Scenario: Validate full create Schedule JSON
    Given The following JSON:
    """
    {
        "JsonScheduleV1": {
            "CIF_bank_holiday_running": null,
            "CIF_stp_indicator": "P",
            "CIF_train_uid": "C72592",
            "applicable_timetable": "Y",
            "atoc_code": "VT",
            "new_schedule_segment": {
                "traction_class": "",
                "uic_code": ""
            },
            "schedule_days_runs": "0000010",
            "schedule_end_date": "2020-05-16",
            "schedule_segment": {
                "signalling_id": "1A54",
                "CIF_train_category": "XX",
                "CIF_headcode": "7827",
                "CIF_course_indicator": 1,
                "CIF_train_service_code": "22108001",
                "CIF_business_sector": "??",
                "CIF_power_type": "EMU",
                "CIF_timing_load": "390",
                "CIF_speed": "125",
                "CIF_operating_characteristics": null,
                "CIF_train_class": "B",
                "CIF_sleepers": null,
                "CIF_reservations": "S",
                "CIF_connection_indicator": null,
                "CIF_catering_code": "C",
                "CIF_service_branding": "",
                "schedule_location": [
                    {
                        "location_type": "LO",
                        "record_identity": "LO",
                        "tiploc_code": "MNCRPIC",
                        "tiploc_instance": null,
                        "departure": "1615",
                        "public_departure": "1615",
                        "platform": "6",
                        "line": "FL",
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "ARDWCKJ",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1617",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": null,
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": "H",
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "SLDLJN",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1619",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": null,
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "HTNOJN",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1621",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": null,
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "STKP",
                        "tiploc_instance": null,
                        "arrival": "1622H",
                        "departure": "1624",
                        "pass": null,
                        "public_arrival": "1622",
                        "public_departure": "1623",
                        "platform": "2",
                        "line": null,
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "STKPE1",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1625",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": null,
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "ADSWDRD",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1626H",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": null,
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "CHDH",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1627H",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": "4",
                        "line": null,
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "MACLSFD",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1634H",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": "2",
                        "line": null,
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "CONGLTN",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1639H",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": null,
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "KIDSGRV",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1642H",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": null,
                        "path": null,
                        "engineering_allowance": "1",
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "STOKEOT",
                        "tiploc_instance": null,
                        "arrival": "1648H",
                        "departure": "1650H",
                        "pass": null,
                        "public_arrival": "1649",
                        "public_departure": "1650",
                        "platform": "1",
                        "line": null,
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "STOKOTJ",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1651H",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": null,
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "STONE",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1656",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": null,
                        "path": null,
                        "engineering_allowance": "1",
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "COLWICH",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1704H",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": "FL",
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "RUGLYNJ",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1707",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": "FL",
                        "path": "FL",
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "LCHTNJ",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1711",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": "FL",
                        "path": "FL",
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "AMNGTNJ",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1714H",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": "FL",
                        "path": "FL",
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "NNTN",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1720H",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": "4",
                        "line": "FL",
                        "path": "FL",
                        "engineering_allowance": "1",
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "RUGBTVJ",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1728",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": "FL",
                        "path": "FL",
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "RUGBY",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1728H",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": "4",
                        "line": "FL",
                        "path": "FL",
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "HMTNJ",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1729",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": null,
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "WEEDON",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1735",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": "FL",
                        "path": "FL",
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "HANSLPJ",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1741H",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": "FL",
                        "path": "FL",
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "MKNSCEN",
                        "tiploc_instance": null,
                        "arrival": "1745H",
                        "departure": "1747H",
                        "pass": null,
                        "public_arrival": "1746",
                        "public_departure": "1747",
                        "platform": "4",
                        "line": "FL",
                        "path": "FL",
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "BLTCHLY",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1750H",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": "2",
                        "line": "FL",
                        "path": "FL",
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "LEDBRNJ",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1755",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": "FL",
                        "path": "FL",
                        "engineering_allowance": "1",
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "TRING",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1758H",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": "2",
                        "line": "FL",
                        "path": "FL",
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "BONENDJ",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1801H",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": "FL",
                        "path": "FL",
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "WATFDJ",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1805H",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": "7",
                        "line": "FL",
                        "path": "FL",
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "HROW",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1809",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": "4",
                        "line": "FL",
                        "path": "FL",
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "WMBY",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1811",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": "4",
                        "line": null,
                        "path": null,
                        "engineering_allowance": "1",
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "WLSDWLJ",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1813H",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": "FL",
                        "path": "FL",
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "CMDNJN",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1816H",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": "A",
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "CMDNSTH",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1817",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": null,
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LT",
                        "record_identity": "LT",
                        "tiploc_code": "EUSTON",
                        "tiploc_instance": null,
                        "arrival": "1820",
                        "public_arrival": "1820",
                        "platform": "6",
                        "path": null
                    }
                ]
            },
            "schedule_start_date": "2019-12-21",
            "train_status": "P",
            "transaction_type": "Create"
        }
    }
    """
    When it's validated against "network-rail-schedule-schedule.schema.json"
    Then it should pass validation

  Scenario: Validate bank holiday running Schedule JSON
    Given The following JSON:
    """
    {
        "JsonScheduleV1": {
            "CIF_bank_holiday_running": "X",
            "CIF_stp_indicator": "P",
            "CIF_train_uid": "Y93657",
            "applicable_timetable": "Y",
            "atoc_code": "AW",
            "new_schedule_segment": {
                "traction_class": "",
                "uic_code": ""
            },
            "schedule_days_runs": "1111110",
            "schedule_end_date": "2020-05-16",
            "schedule_segment": {
                "signalling_id": "0B00",
                "CIF_train_category": "BS",
                "CIF_headcode": "",
                "CIF_course_indicator": 1,
                "CIF_train_service_code": "25448000",
                "CIF_business_sector": "??",
                "CIF_power_type": null,
                "CIF_timing_load": null,
                "CIF_speed": null,
                "CIF_operating_characteristics": null,
                "CIF_train_class": null,
                "CIF_sleepers": null,
                "CIF_reservations": null,
                "CIF_connection_indicator": null,
                "CIF_catering_code": null,
                "CIF_service_branding": "",
                "schedule_location": [
                    {
                        "location_type": "LO",
                        "record_identity": "LO",
                        "tiploc_code": "YSTRADM",
                        "tiploc_instance": null,
                        "departure": "0722",
                        "public_departure": "0722",
                        "platform": null,
                        "line": "BUS",
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LT",
                        "record_identity": "LT",
                        "tiploc_code": "YSTRBWD",
                        "tiploc_instance": null,
                        "arrival": "0738",
                        "public_arrival": "0738",
                        "platform": null,
                        "path": null
                    }
                ]
            },
            "schedule_start_date": "2019-12-16",
            "train_status": "B",
            "transaction_type": "Create"
        }
    }
    """

  Scenario: Validate full freight Schedule JSON with empty headcode and category
    Given The following JSON:
    """
    {
        "JsonScheduleV1": {
            "CIF_bank_holiday_running": null,
            "CIF_stp_indicator": "P",
            "CIF_train_uid": "H01603",
            "applicable_timetable": "Y",
            "atoc_code": "ZZ",
            "new_schedule_segment": {
                "traction_class": "",
                "uic_code": ""
            },
            "schedule_days_runs": "0000010",
            "schedule_end_date": "2020-05-16",
            "schedule_segment": {
                "signalling_id": null,
                "CIF_train_category": null,
                "CIF_headcode": "",
                "CIF_course_indicator": 1,
                "CIF_train_service_code": "55460185",
                "CIF_business_sector": "??",
                "CIF_power_type": "D",
                "CIF_timing_load": "800",
                "CIF_speed": "075",
                "CIF_operating_characteristics": null,
                "CIF_train_class": null,
                "CIF_sleepers": null,
                "CIF_reservations": null,
                "CIF_connection_indicator": null,
                "CIF_catering_code": null,
                "CIF_service_branding": "",
                "schedule_location": [
                    {
                        "location_type": "LO",
                        "record_identity": "LO",
                        "tiploc_code": "SOTDWGB",
                        "tiploc_instance": null,
                        "departure": "1133",
                        "public_departure": null,
                        "platform": null,
                        "line": null,
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "MBRKDX",
                        "tiploc_instance": null,
                        "arrival": "1143",
                        "departure": "1146",
                        "pass": null,
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": "DFL",
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "SOTON",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1150",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": "2",
                        "line": null,
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "NTHMJN",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1152",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": "FL",
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": "H",
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "STDENYS",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1154",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": null,
                        "line": null,
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": "1",
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "SOTPKWY",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1158",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": "1",
                        "line": "FL",
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": "1H",
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LI",
                        "record_identity": "LI",
                        "tiploc_code": "ELGH",
                        "tiploc_instance": null,
                        "arrival": null,
                        "departure": null,
                        "pass": "1203H",
                        "public_arrival": null,
                        "public_departure": null,
                        "platform": "2",
                        "line": null,
                        "path": null,
                        "engineering_allowance": null,
                        "pathing_allowance": null,
                        "performance_allowance": null
                    },
                    {
                        "location_type": "LT",
                        "record_identity": "LT",
                        "tiploc_code": "ELGHENY",
                        "tiploc_instance": null,
                        "arrival": "1207",
                        "public_arrival": null,
                        "platform": null,
                        "path": null
                    }
                ]
            },
            "schedule_start_date": "2019-12-21",
            "train_status": "F",
            "transaction_type": "Create"
        }
    }
    """
    When it's validated against "network-rail-schedule-schedule.schema.json"
    Then it should pass validation

  Scenario: Validate STP overlay Schedule JSON
    Given The following JSON:
    """
    {
        "JsonScheduleV1": {
            "CIF_bank_holiday_running": null,
            "CIF_stp_indicator": "C",
            "CIF_train_uid": "C72592",
            "schedule_days_runs": "0000010",
            "schedule_end_date": "2020-05-02",
            "schedule_segment": {
                "signalling_id": "    ",
                "CIF_train_category": "",
                "CIF_headcode": "",
                "CIF_course_indicator": 1,
                "CIF_train_service_code": "        ",
                "CIF_business_sector": "??",
                "CIF_power_type": null,
                "CIF_timing_load": null,
                "CIF_speed": null,
                "CIF_operating_characteristics": null,
                "CIF_train_class": null,
                "CIF_sleepers": null,
                "CIF_reservations": null,
                "CIF_connection_indicator": null,
                "CIF_catering_code": null,
                "CIF_service_branding": ""
            },
            "schedule_start_date": "2020-05-02",
            "train_status": " ",
            "transaction_type": "Create"
        }
    }
    """
    When it's validated against "network-rail-schedule-schedule.schema.json"
    Then it should pass validation

  Scenario: Validate full delete Schedule JSON
    Given The following JSON:
    """
    {
        "JsonScheduleV1": {
            "CIF_train_uid": "Y95842",
            "schedule_start_date": "2020-04-04",
            "CIF_stp_indicator": "O",
            "transaction_type": "Delete"
        }
    }
    """
    When it's validated against "network-rail-schedule-schedule.schema.json"
    Then it should pass validation
